name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy ninja-build openssl libssl-dev

    - name: Check code formatting
      run: uv run scripts/format.py --check

    - uses: lukka/get-cmake@latest

    - name: Build
      run: uv run scripts/build.py --mode ${{ matrix.build_type }} --tests --export-compile-commands

    - name: Run tests
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }} --output-on-failure --parallel
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}