name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install clang-format and clang-tidy
      run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy

    - name: Check code formatting
      run: uv run scripts/format.py --check

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install dependencies with vcpkg
      run: vcpkg install --triplet=x64-linux --x-feature=tests

    - name: Build
      run: uv run scripts/build.py --mode ${{ matrix.build_type }} --tests --export-compile-commands

    - name: Run tests
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }} --output-on-failure --parallel
